// This file is @generated by prost-build.
/// OAuth Token 结构 (三层嵌套)
/// 数据库存储: Base64(OAuthTokenWrapper)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OAuthTokenWrapper {
    #[prost(message, optional, tag = "1")]
    pub inner: ::core::option::Option<OAuthTokenInner>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OAuthTokenInner {
    /// "oauthTokenInfoSentinelKey"
    #[prost(string, tag = "1")]
    pub sentinel_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<OAuthTokenData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OAuthTokenData {
    /// Base64(OAuthInfo)
    #[prost(string, tag = "1")]
    pub oauth_info_base64: ::prost::alloc::string::String,
}
/// OAuthInfo (需要单独 Base64 解码)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OAuthInfo {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// "Bearer"
    #[prost(string, tag = "2")]
    pub token_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub expiry: ::core::option::Option<Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
}
/// Override Store 结构
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverrideStoreWrapper {
    #[prost(message, optional, tag = "1")]
    pub inner: ::core::option::Option<OverrideStoreInner>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverrideStoreInner {
    /// "secureModeEnabledSentinelKey"
    #[prost(string, tag = "1")]
    pub sentinel_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<OverrideStoreData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverrideStoreData {
    /// "CAA=" = false, "CAE=" = true
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// User Status 结构
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserStatusWrapper {
    #[prost(message, optional, tag = "1")]
    pub inner: ::core::option::Option<UserStatusInner>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserStatusInner {
    /// "userStatusSentinelKey"
    #[prost(string, tag = "1")]
    pub sentinel_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<UserStatusData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserStatusData {
    /// Base64 encoded data
    #[prost(string, tag = "1")]
    pub raw_data: ::prost::alloc::string::String,
}
/// User Status 原始内容（raw_data）对应结构
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserContext {
    #[prost(int32, tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub plan_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "33")]
    pub models: ::core::option::Option<AppConfig>,
    #[prost(message, optional, tag = "36")]
    pub plan: ::core::option::Option<Subscription>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppConfig {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ModelConfig>,
    #[prost(message, optional, tag = "2")]
    pub recommended: ::core::option::Option<RecommendedModels>,
    #[prost(message, optional, tag = "3")]
    pub default_model: ::core::option::Option<DefaultModel>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub id: ::core::option::Option<ModelId>,
    #[prost(int32, tag = "5")]
    pub field_5: i32,
    #[prost(int32, tag = "11")]
    pub field_11: i32,
    #[prost(message, optional, tag = "15")]
    pub meta: ::core::option::Option<ModelMeta>,
    #[prost(string, tag = "16")]
    pub tag: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "18")]
    pub supported_types: ::prost::alloc::vec::Vec<MimeTypeSupport>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelId {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ModelMeta {
    #[prost(float, tag = "1")]
    pub rate_limit: f32,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<MetaTimestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetaTimestamp {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MimeTypeSupport {
    #[prost(string, tag = "1")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub enabled: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecommendedModels {
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub list: ::core::option::Option<RecommendedList>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecommendedList {
    #[prost(string, repeated, tag = "2")]
    pub model_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DefaultModel {
    #[prost(message, optional, tag = "1")]
    pub model: ::core::option::Option<ModelId>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Subscription {
    #[prost(string, tag = "1")]
    pub tier_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tier_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub upgrade_url: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub upgrade_message: ::prost::alloc::string::String,
}
